### 1. Import Dependencies

In [8]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [9]:
df = pd.read_csv("./data/processed/ChurnModeling_Feature_Encoding_Applied.csv")
df.head()

,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geogeraphy_France,Geogeraphy_Germany,Geogeraphy_Spain,Gender_Female,Gender_Male
0,42.00,2,0.00,1,1,1,101348.88,1,Fair,True,False,False,True,False
1,41.00,1,83807.86,1,0,1,112542.58,0,Fair,False,False,True,True,False
2,42.00,8,159660.80,3,1,0,113931.57,1,Poor,True,False,False,True,False
3,38.91,1,0.00,2,0,0,93826.63,0,Good,True,False,False,True,False
4,43.00,2,125510.82,1,1,1,79084.10,0,Excellent,False,False,True,True,False

In [10]:
print(df['Tenure'].max())

10

In [15]:
columns_needed_to_be_scaled = ['Age', 'Tenure', 'Balance', 'EstimatedSalary']

for col in columns_needed_to_be_scaled:
    standard_scalar = StandardScaler()
    df[col] = standard_scalar.fit_transform(df[col].values.reshape(10000,1))

In [16]:
df.head()

,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,CreditScoreBins,Geogeraphy_France,Geogeraphy_Germany,Geogeraphy_Spain,Gender_Female,Gender_Male
0,0.302983,-1.041760,-1.225848,1,1,1,0.021886,1,Fair,True,False,False,True,False
1,0.204867,-1.387538,0.117350,1,0,1,0.216534,0,Fair,False,False,True,True,False
2,0.302983,1.032908,1.333053,3,1,0,0.240687,1,Poor,True,False,False,True,False
3,-0.000196,-1.387538,-1.225848,2,0,0,-0.108918,0,Good,True,False,False,True,False
4,0.401100,-1.041760,0.785728,1,1,1,-0.365276,0,Excellent,False,False,True,True,False

In [17]:
df.to_csv("./data/processed/ChurnModeling_Feature_Scaling_Applied.csv", index=False)